# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        StackedWidget.setObjectName("StackedWidget")
        StackedWidget.resize(402, 357)
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.startButton = QtWidgets.QPushButton(self.page1)
        self.startButton.setGeometry(QtCore.QRect(120, 220, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.titleLabel = QtWidgets.QLabel(self.page1)
        self.titleLabel.setGeometry(QtCore.QRect(90, 100, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.descLabel = QtWidgets.QLabel(self.page1)
        self.descLabel.setGeometry(QtCore.QRect(40, 160, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setItalic(True)
        self.descLabel.setFont(font)
        self.descLabel.setObjectName("descLabel")
        StackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.label = QtWidgets.QLabel(self.page2)
        self.label.setGeometry(QtCore.QRect(50, 110, 301, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page2)
        self.label_2.setGeometry(QtCore.QRect(170, 60, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.chooseVideoDirButton = QtWidgets.QPushButton(self.page2)
        self.chooseVideoDirButton.setGeometry(QtCore.QRect(110, 230, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.chooseVideoDirButton.setFont(font)
        self.chooseVideoDirButton.setObjectName("chooseVideoDirButton")
        StackedWidget.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.label_3 = QtWidgets.QLabel(self.page3)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.page3)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 371, 141))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.roiTimer = QtWidgets.QLCDNumber(self.page3)
        self.roiTimer.setGeometry(QtCore.QRect(180, 270, 91, 51))
        self.roiTimer.setSmallDecimalPoint(False)
        self.roiTimer.setDigitCount(3)
        self.roiTimer.setProperty("value", 30.0)
        self.roiTimer.setProperty("intValue", 30)
        self.roiTimer.setObjectName("roiTimer")
        self.label_5 = QtWidgets.QLabel(self.page3)
        self.label_5.setGeometry(QtCore.QRect(20, 280, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        StackedWidget.addWidget(self.page3)
        self.page4 = QtWidgets.QWidget()
        self.page4.setObjectName("page4")
        self.label_6 = QtWidgets.QLabel(self.page4)
        self.label_6.setGeometry(QtCore.QRect(30, 50, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page4)
        self.label_7.setGeometry(QtCore.QRect(170, 150, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.resetButton = QtWidgets.QPushButton(self.page4)
        self.resetButton.setGeometry(QtCore.QRect(140, 210, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.resetButton.setFont(font)
        self.resetButton.setObjectName("resetButton")
        self.roiTimer_2 = QtWidgets.QLCDNumber(self.page4)
        self.roiTimer_2.setGeometry(QtCore.QRect(240, 290, 91, 51))
        self.roiTimer_2.setSmallDecimalPoint(False)
        self.roiTimer_2.setDigitCount(3)
        self.roiTimer_2.setProperty("value", 30.0)
        self.roiTimer_2.setProperty("intValue", 30)
        self.roiTimer_2.setObjectName("roiTimer_2")
        self.label_8 = QtWidgets.QLabel(self.page4)
        self.label_8.setGeometry(QtCore.QRect(80, 300, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        StackedWidget.addWidget(self.page4)

        self.retranslateUi(StackedWidget)
        StackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(StackedWidget)
        return StackedWidget

    def retranslateUi(self, StackedWidget):
        _translate = QtCore.QCoreApplication.translate
        StackedWidget.setWindowTitle(_translate("StackedWidget", "StackedWidget"))
        self.startButton.setText(_translate("StackedWidget", "Start"))
        self.titleLabel.setText(_translate("StackedWidget", "GAITOR"))
        self.descLabel.setText(_translate("StackedWidget", "Video Analysis of Rats in a Gait Maze"))
        self.label.setText(_translate("StackedWidget", "Before continuing, please make sure to create a directory containing your video files."))
        self.label_2.setText(_translate("StackedWidget", "Note:"))
        self.chooseVideoDirButton.setText(_translate("StackedWidget", "Choose Video Folder"))
        self.label_3.setText(_translate("StackedWidget", "Select Region of Interest (ROI):"))
        self.label_4.setText(_translate("StackedWidget", "In the video window... \n"
"1. Click TOP boundary of track. \n"
"2. Click BOTTOM boundary of track. \n"
"3. Click LEFT boundary of track. \n"
"4. Click RIGHT boundary of track. \n"
"5. Press ANY KEY to see ROI."))
        self.label_5.setText(_translate("StackedWidget", "Time Remaining:"))
        self.label_6.setText(_translate("StackedWidget", "Keep ROI and Continue:\n"
"Press ANY KEY"))
        self.label_7.setText(_translate("StackedWidget", "OR"))
        self.resetButton.setText(_translate("StackedWidget", "Reset"))
        self.label_8.setText(_translate("StackedWidget", "Time Remaining:"))

